# Generated by Django 3.0.4 on 2020-04-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bio',
        ),
    ]
